# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uInZ8hUKIbXOPG2G8XMGt-NQgYBOqgTg
"""

import pandas as pd
import numpy as np
import warnings

#Dataframe for array
df = pd.read_csv('ratings.csv')

#Getting out the required column for the array
df = df[['userId','movieId','rating']]

#Using Pandas Pivot for Generating The Required DataFrame
df = df.pivot('userId','movieId','rating')

#Filling nan values
df = df.fillna(0)
df

#Converting The DataFrame to Array
arr = np.array(df)

#Displaying the Array
print(arr)

pip install sparsesvd

import scipy.sparse
from sparsesvd import sparsesvd

smat = scipy.sparse.csc_matrix(arr) # convert to sparse CSC format

ut, s, vt = sparsesvd(smat, 50) # do SVD, asking for 55 factors

print(s.size)

predicted_Ratings = np.dot(ut.T, np.dot(np.diag(s), vt))
print(predicted_Ratings)

from sklearn.metrics import mean_squared_error
from math import sqrt

sub_matrix = np.subtract(arr, predicted_Ratings)
squared_matrix = np.square(sub_matrix)

#Calculating RMSE and MSE
mse = squared_matrix[~np.isnan(squared_matrix)].mean()
rmse = sqrt(mse)

#Printing RMSE and MSE
print(rmse) #0.30609639616977774
print(mse) #0.09369500374812553

